import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { motion } from 'framer-motion';
import { Upload, FileText, Download } from 'lucide-react';
import { toast } from 'sonner';
import { jsPDF } from 'jspdf';

const ResumeAnalyzer = () => {
  const [userInfo, setUserInfo] = useState(null);
  const [resumeFile, setResumeFile] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [resumeData, setResumeData] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    const user = localStorage.getItem('userInfo');
    if (!user) {
      navigate('/login');
    } else {
      const parsedUser = JSON.parse(user);
      setUserInfo(parsedUser);
      fetchLatestResume(parsedUser.token);
    }
  }, [navigate]);

  const fetchLatestResume = async (token) => {
    try {
      const config = { headers: { Authorization: `Bearer ${token}` } };
      const resumeRes = await axios.get(`${import.meta.env.VITE_API_URL}/api/resumes`, config);
      if (resumeRes.data && resumeRes.data.length > 0) {
        setResumeData(resumeRes.data[0]);
      }
    } catch (err) {
      toast.error('Failed to load resume data');
    }
  };

  const uploadFileHandler = async (e) => {
    e.preventDefault();
    if (!resumeFile) return;

    setUploading(true);
    const formData = new FormData();
    formData.append('resume', resumeFile);

    try {
      const config = {
        headers: {
          'Content-Type': 'multipart/form-data',
          Authorization: `Bearer ${userInfo.token}`,
        },
      };

      const { data } = await axios.post(`${import.meta.env.VITE_API_URL}/api/resumes/upload`, formData, config);
      setResumeData(data);
      setResumeFile(null);
      toast.success('Resume analyzed successfully!');
    } catch (err) {
      toast.error(err.response?.data?.message || err.message);
    } finally {
      setUploading(false);
    }
  };

  const downloadReport = () => {
    if (!resumeData) return;
    const doc = new jsPDF();
    
    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.setTextColor(79, 70, 229);
    doc.text('InterviewAI', 20, 25);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(18);
    doc.setTextColor(15, 23, 42);
    doc.text('Resume Analysis Report', 20, 35);

    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    doc.text(`Date Analyzed: ${new Date(resumeData.createdAt).toLocaleDateString()}`, 20, 45);

    doc.setDrawColor(226, 232, 240);
    doc.line(20, 50, 190, 50);

    // Score
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(`Overall ATS Score:`, 20, 65);
    doc.setFontSize(22);
    doc.setTextColor(16, 185, 129);
    doc.text(`${resumeData.atsScore}%`, 70, 65);

    // Skills
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text('Extracted Skills:', 20, 85);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(71, 85, 105);
    const skillsText = resumeData.extractedSkills.join(' • ');
    const splitSkills = doc.splitTextToSize(skillsText, 170);
    doc.text(splitSkills, 20, 95);

    // Feedback
    const feedbackY = 102 + (splitSkills.length * 6);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text('AI Feedback & Suggestions:', 20, feedbackY);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(71, 85, 105);
    const splitFeedback = doc.splitTextToSize(resumeData.feedback, 170);
    doc.text(splitFeedback, 20, feedbackY + 10);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by IntervAI', 20, 280);

    doc.save(`IntervAI_Report_${new Date().getTime()}.pdf`);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-10">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-8"
      >
        <h1 className="text-3xl font-bold tracking-tight text-white mb-2">Resume Analyzer</h1>
        <p className="text-slate-400">Upload your PDF resume to get an AI-powered ATS score and feedback.</p>
      </motion.div>

      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.1 }}
        className="bg-slate-900/50 backdrop-blur-md border border-slate-800 shadow-xl rounded-2xl p-6"
      >
        <div className="flex items-center gap-2 mb-6">
          <FileText className="text-blue-400" />
          <h3 className="text-lg font-semibold text-slate-100">Upload & Analyze</h3>
        </div>
        
        {/* Upload Form */}
        <form onSubmit={uploadFileHandler} className="mb-6 flex flex-col sm:flex-row items-end gap-4 bg-slate-950 p-6 rounded-xl border border-slate-800">
          <div className="flex-grow w-full">
            <input
              type="file"
              id="resume"
              accept="application/pdf"
              onChange={(e) => setResumeFile(e.target.files[0])}
              className="block w-full text-sm text-slate-400 file:mr-4 file:py-2.5 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-semibold file:bg-indigo-600/20 file:text-indigo-400 hover:file:bg-indigo-600/30 transition-colors"
            />
          </div>
          <button
            type="submit"
            disabled={!resumeFile || uploading}
            className="w-full sm:w-auto rounded-lg bg-indigo-600 px-8 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-600/20 hover:bg-indigo-500 disabled:opacity-50 transition-all flex items-center justify-center gap-2"
          >
            <Upload size={16} />
            {uploading ? 'Analyzing...' : 'Analyze Now'}
          </button>
        </form>

        {/* ATS Results */}
        {resumeData && (
          <div className="bg-slate-950/50 rounded-xl p-8 border border-slate-800 relative overflow-hidden mt-8">
            <div className="absolute top-0 right-0 p-4 text-xs text-slate-500 font-mono">
              Last Analyzed: {new Date(resumeData.createdAt).toLocaleDateString()}
            </div>
            
            <div className="flex flex-col sm:flex-row items-start sm:items-center gap-8 mb-8">
              <div className="w-32 h-32 rounded-full border-4 border-indigo-500 flex flex-col items-center justify-center bg-slate-900 shadow-[0_0_20px_rgba(99,102,241,0.3)]">
                <span className="text-4xl font-black text-indigo-400">{resumeData.atsScore}%</span>
                <span className="text-[10px] text-slate-400 uppercase tracking-widest mt-1">ATS Score</span>
              </div>
              <div>
                <h5 className="font-semibold text-slate-200 text-xl mb-2">Analysis Complete</h5>
                <p className="text-slate-400 mb-2">Our AI has extracted your skills and provided feedback to improve your chances.</p>
                <div className="flex items-center gap-3">
                  <a href={resumeData.resumeUrl.startsWith('/uploads') ? `${import.meta.env.VITE_API_URL}${resumeData.resumeUrl}` : resumeData.resumeUrl} target="_blank" rel="noreferrer" className="text-sm text-indigo-400 hover:text-indigo-300 hover:underline inline-flex items-center gap-1 font-medium bg-indigo-500/10 px-3 py-1.5 rounded-lg">
                    View Uploaded Document ↗
                  </a>
                  <button onClick={downloadReport} className="text-sm text-emerald-400 hover:text-emerald-300 hover:underline inline-flex items-center gap-1 font-medium bg-emerald-500/10 px-3 py-1.5 rounded-lg transition-colors cursor-pointer">
                    <Download size={14} /> Download Report
                  </button>
                </div>
              </div>
            </div>

            <div className="mb-8">
              <h5 className="font-medium text-sm text-slate-400 uppercase tracking-wider mb-4">Extracted Skills</h5>
              <div className="flex flex-wrap gap-2">
                {resumeData.extractedSkills.map((skill, index) => (
                  <span key={index} className="inline-flex items-center rounded-lg bg-indigo-500/10 px-4 py-2 text-sm font-medium text-indigo-300 border border-indigo-500/20 shadow-inner">
                    {skill}
                  </span>
                ))}
              </div>
            </div>

            <div>
              <h5 className="font-medium text-sm text-slate-400 uppercase tracking-wider mb-3">AI Feedback</h5>
              <p className="text-base text-slate-300 bg-slate-900 p-6 rounded-xl border border-slate-800 leading-relaxed shadow-inner">
                {resumeData.feedback}
              </p>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  );
};

export default ResumeAnalyzer;
